# Generated by Django 4.2.3 on 2023-07-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmReviewApp', '0002_remove_film_poster_image_film_imdbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='imdbID',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='yoshidashi058@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='film_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filmReviewApp.film'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filmReviewApp.user'),
        ),
    ]
